### ISSUE TITLE
Resolve use of outdated technologies

### ISSUE THREAD

**Issue by treyzania** [jack-michaud/arachnid#1]
Node.js has been shown to have severe performance penalties and unnecessarily increased cognitive load for the developer.  The Phoenix web framework has been proven to be much more efficient and performant than other outdated technologies.

(or just like django, like srsly tho)

**Comment by jack-michaud** [comment]
Hey Trey!
I'm not actually using a Node.js webserver. It sounds like you've been triggered when you saw there was a package.json – I'm actually just using the Gulp to transpile and compress SCSS and Elm into the `dist/` folder.
That being said, the direction that this may be going is an Electron App, which I know you love.

**Comment by treyzania** [comment]
(serious, unironic) REEEEEEEEEEE

So you're making a Dreamweaver clone, except using 10x the memory?

**Comment by jack-michaud** [comment]
where's the ban button

**Comment by jack-michaud** [comment]
In all seriousness, I've been wanting to build a website builder that can build non-static webpages – like Django/Jinja pages or especially React sites.

**Comment by treyzania** [comment]
pls no electron tho

**Comment by treyzania** [comment]
You know what -- you're right Jack. Every choice you made is correct.

**Comment by jack-michaud** [comment]
Thanks Trey! Closing this issue.

**Comment by treyzania** [comment]
Lies.  Someone was using my GitHub account while I was signed in at work!
